/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author rvkul
 */
public class admin_table extends javax.swing.JFrame {

    /**
     * Creates new form admin_table
     */
    public admin_table() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin_breginfo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_reginfo = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_booking = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        admin_breginfo.setText("view register info");
        admin_breginfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_breginfoActionPerformed(evt);
            }
        });
        getContentPane().add(admin_breginfo);
        admin_breginfo.setBounds(121, 16, 177, 52);

        table_reginfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "name", "contact no", "adharno", "city", "password", "email"
            }
        ));
        jScrollPane3.setViewportView(table_reginfo);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(7, 78, 430, 141);

        table_booking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "email", "from city", "to city", "date", "time", "vehical", "status"
            }
        ));
        jScrollPane4.setViewportView(table_booking);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(436, 78, 460, 141);

        jButton1.setText("view bookings");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(569, 13, 206, 58);

        jButton2.setText("back to admin home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(617, 246, 185, 48);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\rvkul\\Documents\\NetBeansProjects\\myproj\\src\\myproj\\image\\java.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 0, 660, 430);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rvkul\\Documents\\NetBeansProjects\\myproj\\src\\myproj\\image\\pure-black-background-f82588d3.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 260, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admin_breginfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_breginfoActionPerformed
 
        Connection con=null;
        PreparedStatement pst=null;
            ResultSet rs=null;
      
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");
           Statement st=con.createStatement();
            String sql="select name,contact,adhar,city,password,email from reginfo";
         
                        pst=con.prepareStatement(sql);
                        
                          
                          rs= pst.executeQuery();
                         table_reginfo.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
                
             
                catch(Exception e){ System.out.println(e);} 
        
            
    }//GEN-LAST:event_admin_breginfoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection con=null;
        PreparedStatement pst=null;
            ResultSet rs=null;
      
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");
           Statement st=con.createStatement();
            String sql="select email,from_city,to_city,date,time,vehicle,booking_status from booking";
         
                        pst=con.prepareStatement(sql);
                        
                          
                          rs= pst.executeQuery();
                         table_booking.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
                
             
                catch(Exception e){ System.out.println(e);} 
        
                                                 
                                                  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      new adminhome().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_breginfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable table_booking;
    private javax.swing.JTable table_reginfo;
    // End of variables declaration//GEN-END:variables
}
