/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author rvkul
 */
public class admin_booking_status extends javax.swing.JFrame {

    /**
     * Creates new form admin_booking_status
     */
    public admin_booking_status() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        com_fromcity = new javax.swing.JComboBox();
        com_tocity = new javax.swing.JComboBox();
        com_status = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        com_time = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl22 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        b_updatestatus = new javax.swing.JButton();
        com_amount = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Users email ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 99, 34);
        getContentPane().add(txt_email);
        txt_email.setBounds(90, 30, 222, 36);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("From City");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 90, 55, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To City");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 130, 40, 30);

        com_fromcity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad", "Solapur", "Dhule", "Amaravati", "Nashik", "Kolhapur", "Nanded", "Sangli", "Thane", "Akola", "Latur", "Jalgaon", "Ahmednagar", "Sangli", "Kolhapur", "Chandrapur", "Parbhani", "Jalna", "Jalgaon", "Panvel", "Panvel", "Satara", "Beed", "Yavatmal", "Nagpur", "Gondia", "Solapur", "Amravati", "Osmanabad", "Nandurbar", "Wardha", "Latur", "Wardha" }));
        getContentPane().add(com_fromcity);
        com_fromcity.setBounds(90, 80, 222, 34);

        com_tocity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad", "Solapur", "Dhule", "Amaravati", "Nashik", "Kolhapur", "Nanded", "Sangli", "Thane", "Akola", "Latur", "Jalgaon", "Ahmednagar", "Sangli", "Kolhapur", "Chandrapur", "Parbhani", "Jalna", "Jalgaon", "Panvel", "Panvel", "Satara", "Beed", "Yavatmal", "Nagpur", "Gondia", "Solapur", "Amravati", "Osmanabad", "Nandurbar", "Wardha", "Latur", "Wardha" }));
        getContentPane().add(com_tocity);
        com_tocity.setBounds(90, 120, 222, 40);

        com_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "pending ", "accepted ", "rejected" }));
        com_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_statusActionPerformed(evt);
            }
        });
        getContentPane().add(com_status);
        com_status.setBounds(90, 220, 222, 33);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Time");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 180, 60, 16);

        com_time.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12  A.M", "1    A.M", "2    A.M", "3    A.M", "4    A.M", "5    A.M", "6    A.M", "7    A.M", "8    A.M", "9    A.M", "10  A.M", "11  A.M", "12  P.M", "1    P.M", "2    P.M", "3    P.M", "4    P.M", "5    P.M", "6    P.M", "7    P.M", "8    P.M", "9    P.M", "10  P.M", "11  P.M", "12  P.M" }));
        getContentPane().add(com_time);
        com_time.setBounds(90, 170, 222, 41);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Status");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 220, 93, 26);

        jButton3.setText("view record");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(420, 160, 120, 30);

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "From City", "To City", "Amount"
            }
        ));
        jScrollPane1.setViewportView(tbl1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 210, 260, 50);

        tbl22.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "email", "form city", "to city", "time"
            }
        ));
        jScrollPane2.setViewportView(tbl22);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(330, 50, 310, 100);

        jButton2.setText("back to home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(509, 10, 120, 25);

        b_updatestatus.setText("update status");
        b_updatestatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updatestatusActionPerformed(evt);
            }
        });
        getContentPane().add(b_updatestatus);
        b_updatestatus.setBounds(60, 380, 271, 39);

        com_amount.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50   Rs ", "100 Rs ", "120 Rs ", "140 Rs ", "160 Rs ", "180 Rs ", "200 Rs ", "220 Rs ", "240 Rs ", "260 Rs ", "280 Rs ", "300 Rs " }));
        getContentPane().add(com_amount);
        com_amount.setBounds(90, 270, 220, 40);

        jButton1.setText("genrate amount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 280, 123, 25);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Amount");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 280, 60, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\rvkul\\Documents\\NetBeansProjects\\myproj\\src\\myproj\\image\\java.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 645, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void com_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_statusActionPerformed

    private void b_updatestatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updatestatusActionPerformed
       
         String email=txt_email.getText(); 
     String status= com_status .getSelectedItem().toString();    
        String fromcity= com_fromcity .getSelectedItem().toString();    
        String tocity= com_tocity .getSelectedItem().toString();    
        String time= com_time.getSelectedItem().toString(); 
        String amount= com_amount .getSelectedItem().toString();
     
     
        Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");
             //   pst=con.prepareStatement("insert into booking(email)select email from reginfo");
                    //UPDATE table_name SET field1 = new-value1, field2 = new-value2
                 
                 pst=con.prepareStatement("update booking set booking_status=? , amount=? where email=?and from_city=? and to_city=? and time=?  ");
                pst.setString(1,status);
                pst.setString(2,amount);
                 pst.setString(3,email);
                  pst.setString(4,fromcity);
                 pst.setString(5,tocity);
                 pst.setString(6, time);
                
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null,"status has been updated");
              
          }
          else{
              JOptionPane.showMessageDialog(null,"no record found");
          }
                
                }
                
                catch(Exception e){ System.out.println(e);} 
        
        
        
        
        
       
    }//GEN-LAST:event_b_updatestatusActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new adminhome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   String fromcity= com_fromcity .getSelectedItem().toString();    
        String tocity= com_tocity .getSelectedItem().toString();  
        
        
        Connection con=null;
        PreparedStatement pst=null;
            ResultSet rs=null;
      
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");
           Statement st=con.createStatement();
            String sql="select from_city,to_city,amount from amount where from_city=? and to_city=?";
         
                        pst=con.prepareStatement(sql);
                            pst.setString(1,fromcity);
                            pst.setString(2,tocity);
                          
                          rs= pst.executeQuery();
                         tbl1.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
                
             
                catch(Exception e){ System.out.println(e);} 
                
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 Connection con=null;
        PreparedStatement pst=null;
            ResultSet rs=null;
      
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");
           Statement st=con.createStatement();
            String sql="select email,from_city,to_city ,time  from booking";
         
                        pst=con.prepareStatement(sql);
                        
                          
                          rs= pst.executeQuery();
                         tbl22.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
                
             
                catch(Exception e){ System.out.println(e);} 
                
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_booking_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_booking_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_booking_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_booking_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_booking_status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_updatestatus;
    private javax.swing.JComboBox com_amount;
    private javax.swing.JComboBox com_fromcity;
    private javax.swing.JComboBox com_status;
    private javax.swing.JComboBox com_time;
    private javax.swing.JComboBox com_tocity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl22;
    private javax.swing.JTextField txt_email;
    // End of variables declaration//GEN-END:variables
}
