/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author rvkul
 */
public class admin_login extends javax.swing.JFrame {

    /**
     * Creates new form admin_login
     */
    public admin_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        b_adminlogin = new javax.swing.JButton();
        txt_adminid = new javax.swing.JTextField();
        txt_adminpass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Id ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 90, 105, 31);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 120, 105, 42);

        b_adminlogin.setText("Log In ");
        b_adminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_adminloginActionPerformed(evt);
            }
        });
        getContentPane().add(b_adminlogin);
        b_adminlogin.setBounds(60, 170, 161, 48);
        getContentPane().add(txt_adminid);
        txt_adminid.setBounds(140, 100, 158, 22);
        getContentPane().add(txt_adminpass);
        txt_adminpass.setBounds(140, 130, 158, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Admin Log In Page");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 20, 301, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\rvkul\\Documents\\NetBeansProjects\\myproj\\src\\myproj\\image\\java.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 640, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_adminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_adminloginActionPerformed
      String id=txt_adminid.getText();
      String pass=txt_adminpass.getText();
        
        Connection con=null;
        PreparedStatement pst=null;
        ResultSet rst=null;
        try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");  
             
                 
//    query for insert data into table 

                  pst=con.prepareStatement("  Select id,password from admin where id=? and password=?");
                
            pst.setString(1,id);
            pst.setString(2,pass);
            
              rst= pst.executeQuery();
          if (rst.next()) 
					{
                        // new home().setVisible(true);
                        //this.setVisible(false);	
                        JOptionPane.showMessageDialog(null, "access granted");
                        new adminhome().setVisible(true);
                        this.setVisible(false);	
                    } 
         
          else 
					{
                        JOptionPane.showMessageDialog(null, "access denied");
                    }
				  
			//new home().setVisible(true);
                        //this.setVisible(false);			
				
            
      // new reginfo().setVisible(true);

          // this.setVisible(false);     
}catch(Exception e){ System.out.println(e);}         
           
        
        
      
    }//GEN-LAST:event_b_adminloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_adminlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_adminid;
    private javax.swing.JTextField txt_adminpass;
    // End of variables declaration//GEN-END:variables
}
