/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author rvkul
 */
public class admin_amount extends javax.swing.JFrame {

    /**
     * Creates new form admin_amount
     */
    public admin_amount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        com_from = new javax.swing.JComboBox();
        com_to = new javax.swing.JComboBox();
        b_set = new javax.swing.JButton();
        com_am = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        com_from.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad", "Solapur", "Dhule", "Amaravati", "Kolhapur", "Nanded", "Sangli", "Akola", "Latur", "Jalgaon", "Ahmednagar", "Kolhapur", "Chandrapur", "Parbhani", "Jalna", "Jalgaon", "Panvel", "Satara", "Beed", "Yavatmal", "Nagpur", "Gondia", "Solapur", "Amravati", "Osmanabad", "Nandurbar", "Wardha", "Latur", "Wardha" }));
        com_from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_fromActionPerformed(evt);
            }
        });
        getContentPane().add(com_from);
        com_from.setBounds(22, 126, 100, 22);

        com_to.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad", "Solapur", "Dhule", "Amaravati", "Kolhapur", "Nanded", "Sangli", "Akola", "Latur", "Jalgaon", "Ahmednagar", "Kolhapur", "Chandrapur", "Parbhani", "Jalna", "Jalgaon", "Panvel", "Satara", "Beed", "Yavatmal", "Nagpur", "Gondia", "Solapur", "Amravati", "Osmanabad", "Nandurbar", "Wardha", "Latur", "Wardha" }));
        getContentPane().add(com_to);
        com_to.setBounds(149, 126, 100, 22);

        b_set.setText("set");
        b_set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_setActionPerformed(evt);
            }
        });
        getContentPane().add(b_set);
        b_set.setBounds(130, 180, 138, 25);

        com_am.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  50 Rs ", "100 Rs ", "120 Rs ", "140 Rs ", "160 Rs ", "180 Rs ", "200 Rs ", "220 Rs ", "240 Rs ", "260 Rs ", "280 Rs ", "300 Rs " }));
        getContentPane().add(com_am);
        com_am.setBounds(267, 126, 186, 22);

        jButton1.setText("Back ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 10, 63, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Set Amount");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(122, 48, 282, 29);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("From City");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(43, 103, 55, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To City");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 103, 40, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(289, 103, 44, 16);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\rvkul\\Documents\\NetBeansProjects\\myproj\\src\\myproj\\image\\java.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 650, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_setActionPerformed
 String from_city=com_from.getSelectedItem().toString();
 String to_city=com_to.getSelectedItem().toString();
 String amount=com_am.getSelectedItem().toString();
        
        
        Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");
             //   pst=con.prepareStatement("insert into booking(email)select email from reginfo");
                 pst=con.prepareStatement(" insert into amount values(?,?,?)");
                pst.setString(1, from_city);
                pst.setString(2, to_city);
                pst.setString(3, amount);
              //  pst.setString(4, time);
               // pst.setString(5,value3);
                //pst.setString(6, email);
                //pst.setString(5, email);
              //  pst.setString(5,email);
             //   pst1=con.prepareStatement("insert into booking (name)select name from reginfo");

                 // pst.setInt(3,date);
                //pst.setInt(4,time); 
               // pst=con.prepareStatement("insert into booking(email)select email from reginfo");
                int j= pst.executeUpdate();
          if(j>0)
          {
              //JOptionPane.showMessageDialog(null,"booking successfully");
          }
          else{
            JOptionPane.showMessageDialog(null,"booking not successfully");
          }
               // new home().setVisible(true);
      /// this.setVisible(false);  
                }
                
                
                
                catch(Exception e){ System.out.println(e);} 
        
        
        
        
        
        
        
    }//GEN-LAST:event_b_setActionPerformed

    private void com_fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_fromActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        new adminhome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_amount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_amount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_amount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_amount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_amount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_set;
    private javax.swing.JComboBox com_am;
    private javax.swing.JComboBox com_from;
    private javax.swing.JComboBox com_to;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
