/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author rvkul
 */
public class admin_add extends javax.swing.JFrame {

    /**
     * Creates new form admin_add
     */
    public admin_add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_newaddid = new javax.swing.JTextField();
        txt_newaddpass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Admin ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(24, 79, 173, 40);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Admin Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(24, 133, 173, 59);
        getContentPane().add(txt_newaddid);
        txt_newaddid.setBounds(202, 68, 198, 51);

        txt_newaddpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_newaddpassActionPerformed(evt);
            }
        });
        getContentPane().add(txt_newaddpass);
        txt_newaddpass.setBounds(202, 133, 207, 59);

        jButton1.setText("Add Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 220, 170, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\rvkul\\Documents\\NetBeansProjects\\myproj\\src\\myproj\\image\\java.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, 0, 640, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_newaddpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_newaddpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_newaddpassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String id=txt_newaddid.getText();
      String pass=txt_newaddpass.getText();
        
        Connection con=null;
        PreparedStatement pst=null;
        ResultSet rst=null;
        try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");  
             
                 
//    query for insert data into table 

                  pst=con.prepareStatement("insert into admin values(?,?)");
                
            pst.setString(1,id);
            pst.setString(2,pass);
            int i= pst.executeUpdate();
          if(i>0)
          {
              JOptionPane.showMessageDialog(null,"admin added");
          }
          else{
              JOptionPane.showMessageDialog(null,"admin not added");
          }
            
            new adminhome().setVisible(true);
       this.setVisible(false);
      // new reginfo().setVisible(true);

          // this.setVisible(false);     
}catch(Exception e){ System.out.println(e);}    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_newaddid;
    private javax.swing.JTextField txt_newaddpass;
    // End of variables declaration//GEN-END:variables
}
