/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproj;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author rvkul
 */
public class booking extends javax.swing.JFrame {

    /**
     * Creates new form booking
     */
    public booking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ch_date = new com.toedter.calendar.JDateChooser();
        com_from = new javax.swing.JComboBox();
        com_to = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        com_time = new javax.swing.JComboBox();
        com_car = new javax.swing.JComboBox();
        txt_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("From city");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 60, 89, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("To city");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 89, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 140, 64, 16);

        ch_date.setDateFormatString("d-MMM-yyyy");
        getContentPane().add(ch_date);
        ch_date.setBounds(110, 140, 121, 22);

        com_from.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad", "Solapur", "Dhule", "Amaravati", "Nashik", "Kolhapur", "Nanded", "Sangli", "Thane", "Akola", "Latur", "Jalgaon", "Ahmednagar", "Sangli", "Kolhapur", "Chandrapur", "Parbhani", "Jalna", "Jalgaon", "Panvel", "Panvel", "Satara", "Beed", "Yavatmal", "Nagpur", "Gondia", "Solapur", "Amravati", "Osmanabad", "Nandurbar", "Wardha", "Latur", "Wardha", " " }));
        getContentPane().add(com_from);
        com_from.setBounds(110, 60, 120, 22);

        com_to.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad", "Solapur", "Dhule", "Amaravati", "Nashik", "Kolhapur", "Nanded", "Sangli", "Thane", "Akola", "Latur", "Jalgaon", "Ahmednagar", "Sangli", "Kolhapur", "Chandrapur", "Parbhani", "Jalna", "Jalgaon", "Panvel", "Panvel", "Satara", "Beed", "Yavatmal", "Nagpur", "Gondia", "Solapur", "Amravati", "Osmanabad", "Nandurbar", "Wardha", "Latur", "Wardha", " " }));
        getContentPane().add(com_to);
        com_to.setBounds(110, 100, 121, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Conform your booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 350, 175, 25);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Time");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 180, 29, 16);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("update booking");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 390, 180, 30);

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("If you want to update your booking  click heare");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 390, 340, 29);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Vehicle");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 220, 70, 16);

        com_time.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12  A.M", "1    A.M", "2    A.M", "3    A.M", "4    A.M", "5    A.M", "6    A.M", "7    A.M", "8    A.M", "9    A.M", "10  A.M", "11  A.M", "12  P.M", "1    P.M", "2    P.M", "3    P.M", "4    P.M", "5    P.M", "6    P.M", "7    P.M", "8    P.M", "9    P.M", "10  P.M", "11  P.M", "12  P.M" }));
        getContentPane().add(com_time);
        com_time.setBounds(110, 180, 120, 22);

        com_car.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Car", "GOVT.Bus", "PVT.Bus", "Airplane" }));
        getContentPane().add(com_car);
        com_car.setBounds(110, 220, 120, 20);
        getContentPane().add(txt_email);
        txt_email.setBounds(110, 260, 120, 20);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 250, 80, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\rvkul\\Documents\\NetBeansProjects\\myproj\\src\\myproj\\image\\explor.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 640, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
      String value=com_from.getSelectedItem().toString();
      String value1=com_to.getSelectedItem().toString();
    //date
      Date date= new Date(ch_date.getDate().getTime());
      DateFormat dateFormat=new SimpleDateFormat("d-mmm-yyyy");
      String strDate=dateFormat.format(date);
      
      String time=com_time.getSelectedItem().toString();
      String value3=com_car.getSelectedItem().toString();
      String email=txt_email.getText();
     
     
      
      
      Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");
             //   pst=con.prepareStatement("insert into booking(email)select email from reginfo");
                 pst=con.prepareStatement(" insert into booking (from_city,to_city,date,time,vehicle,email )values(?,?,?,?,?,?)");
                pst.setString(1, value);
                pst.setString(2, value1);
                pst.setDate(3,date);
                pst.setString(4, time);
                pst.setString(5,value3);
                pst.setString(6, email);
               
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null,"booking successfully");
          }
          else{
            JOptionPane.showMessageDialog(null,"booking not successfully");
          }
                new home().setVisible(true);
       this.setVisible(false);  
                }
                
                
                
                catch(Exception e){ System.out.println(e);} 
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new upd_booking().setVisible(true);
       this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser ch_date;
    private javax.swing.JComboBox com_car;
    private javax.swing.JComboBox com_from;
    private javax.swing.JComboBox com_time;
    private javax.swing.JComboBox com_to;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_email;
    // End of variables declaration//GEN-END:variables
}
