/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author rvkul
 */
public class cancle extends javax.swing.JFrame {

    /**
     * Creates new form cancle
     */
    public cancle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_canemail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        com_tocity = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        com_time = new javax.swing.JComboBox();
        com_from = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("If you want to just change location then no need to cancle your ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 13, 569, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 250, 127, 38);
        getContentPane().add(txt_canemail);
        txt_canemail.setBounds(90, 260, 190, 22);

        jButton1.setText("Cancel Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 390, 119, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("time");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 350, 60, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("then also you want to cancel booking then just enter ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 190, 520, 24);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("valid email id  and your booking will be cancled");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 220, 450, 20);

        com_tocity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad", "Solapur", "Dhule", "Amaravati", "Nashik", "Kolhapur", "Nanded", "Sangli", "Thane", "Akola", "Latur", "Jalgaon", "Ahmednagar", "Sangli", "Kolhapur", "Chandrapur", "Parbhani", "Jalna", "Jalgaon", "Panvel", "Panvel", "Satara", "Beed", "Yavatmal", "Nagpur", "Gondia", "Solapur", "Amravati", "Osmanabad", "Nandurbar", "Wardha", "Latur" }));
        getContentPane().add(com_tocity);
        com_tocity.setBounds(90, 320, 190, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("to city");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 320, 70, 22);

        com_time.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12  A.M", "1    A.M", "2    A.M", "3    A.M", "4    A.M", "5    A.M", "6    A.M", "7    A.M", "8    A.M", "9    A.M", "10  A.M", "11  A.M", "12  P.M", "1    P.M", "2    P.M", "3    P.M", "4    P.M", "5    P.M", "6    P.M", "7    P.M", "8    P.M", "9    P.M", "10  P.M", "11  P.M", "12  P.M" }));
        getContentPane().add(com_time);
        com_time.setBounds(90, 350, 190, 22);

        com_from.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad", "Solapur", "Dhule", "Amaravati", "Nashik", "Kolhapur", "Nanded", "Sangli", "Thane", "Akola", "Latur", "Jalgaon", "Ahmednagar", "Sangli", "Kolhapur", "Chandrapur", "Parbhani", "Jalna", "Jalgaon", "Panvel", "Panvel", "Satara", "Beed", "Yavatmal", "Nagpur", "Gondia", "Solapur", "Amravati", "Osmanabad", "Nandurbar", "Wardha", "Latur" }));
        getContentPane().add(com_from);
        com_from.setBounds(90, 290, 190, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("from city ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 290, 90, 22);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Update Booking");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 40, 200, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("you just update ur booking");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 50, 187, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\rvkul\\Documents\\NetBeansProjects\\myproj\\src\\myproj\\image\\nust plane.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 640, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       String email=txt_canemail.getText(); 
        String time= com_time .getSelectedItem().toString();  
        String fromcity= com_from .getSelectedItem().toString();  
        String tocity= com_tocity .getSelectedItem().toString();  
        
        Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");
             //   pst=con.prepareStatement("insert into booking(email)select email from reginfo");
                    //UPDATE table_name SET field1 = new-value1, field2 = new-value2
                 
                 pst=con.prepareStatement("delete from booking where email=? and from_city=? and to_city=? and time=?");
                pst.setString(1,email);
                pst.setString(2,fromcity);
                pst.setString(3,tocity);
                pst.setString(4,time);
                
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null," As per your request, your booking has been cancelled");
              
          }
          else{
              JOptionPane.showMessageDialog(null," enter your valid email id");
          }
                new home().setVisible(true);
       this.setVisible(false);  
                }
                
                catch(Exception e){ System.out.println(e);} 
             
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new upd_booking().setVisible(true);
       this.setVisible(false);    
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cancle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cancle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cancle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cancle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cancle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox com_from;
    private javax.swing.JComboBox com_time;
    private javax.swing.JComboBox com_tocity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_canemail;
    // End of variables declaration//GEN-END:variables
}
