/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproj;

/**
 *
 * @author rvkul
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        b_bknow = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        B_cancle = new javax.swing.JButton();
        b_feedback = new javax.swing.JButton();
        b_bkinfo = new javax.swing.JButton();
        b_updbooking = new javax.swing.JButton();
        b_contactus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        b_bknow.setText("Book Now");
        b_bknow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_bknowActionPerformed(evt);
            }
        });
        getContentPane().add(b_bknow);
        b_bknow.setBounds(30, 160, 153, 25);

        jButton2.setText("log out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(510, 390, 120, 25);

        B_cancle.setText("Cancle Booking ");
        B_cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cancleActionPerformed(evt);
            }
        });
        getContentPane().add(B_cancle);
        B_cancle.setBounds(30, 280, 153, 25);

        b_feedback.setText("Feed Back");
        b_feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_feedbackActionPerformed(evt);
            }
        });
        getContentPane().add(b_feedback);
        b_feedback.setBounds(30, 320, 153, 25);

        b_bkinfo.setText("booking info ");
        b_bkinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_bkinfoActionPerformed(evt);
            }
        });
        getContentPane().add(b_bkinfo);
        b_bkinfo.setBounds(30, 200, 147, 30);

        b_updbooking.setText("Update Booking");
        b_updbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updbookingActionPerformed(evt);
            }
        });
        getContentPane().add(b_updbooking);
        b_updbooking.setBounds(30, 240, 153, 25);

        b_contactus.setText("Contact Us");
        b_contactus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_contactusActionPerformed(evt);
            }
        });
        getContentPane().add(b_contactus);
        b_contactus.setBounds(30, 360, 153, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rvkul\\Documents\\NetBeansProjects\\myproj\\src\\myproj\\image\\glass.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_bknowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_bknowActionPerformed
new booking().setVisible(true);
       this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_b_bknowActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     new Login().setVisible(true);
       this.setVisible(false);  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void B_cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cancleActionPerformed
       new cancle().setVisible(true);
       this.setVisible(false);  
    }//GEN-LAST:event_B_cancleActionPerformed

    private void b_feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_feedbackActionPerformed
       new feed_back().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_b_feedbackActionPerformed

    private void b_updbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updbookingActionPerformed
 new upd_booking().setVisible(true);
 this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_b_updbookingActionPerformed

    private void b_contactusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_contactusActionPerformed
        new contact_us().setVisible(true);
 this.setVisible(false);
    }//GEN-LAST:event_b_contactusActionPerformed

    private void b_bkinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_bkinfoActionPerformed
        new booking_info().setVisible(true);
 this.setVisible(false);
 
 
 
 //Hello
    }//GEN-LAST:event_b_bkinfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_cancle;
    private javax.swing.JButton b_bkinfo;
    private javax.swing.JButton b_bknow;
    private javax.swing.JButton b_contactus;
    private javax.swing.JButton b_feedback;
    private javax.swing.JButton b_updbooking;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
