/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author rvkul
 */
public class reginfo extends javax.swing.JFrame {

    /**
     * Creates
     */
    public reginfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_con = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_adhar = new javax.swing.JTextField();
        com_city = new javax.swing.JComboBox();
        txt_pass = new javax.swing.JPasswordField();
        b_sub = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 60, 70, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contact No");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 90, 80, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 120, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Adhar No");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(430, 150, 70, 16);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("City");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 190, 40, 16);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 220, 70, 16);
        getContentPane().add(txt_name);
        txt_name.setBounds(510, 60, 120, 20);
        getContentPane().add(txt_con);
        txt_con.setBounds(510, 90, 126, 20);
        getContentPane().add(txt_email);
        txt_email.setBounds(510, 120, 126, 20);
        getContentPane().add(txt_adhar);
        txt_adhar.setBounds(510, 150, 126, 20);

        com_city.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad", "Solapur", "Dhule", "Amaravati", "Nashik", "Kolhapur", "Nanded", "Sangli", "Thane", "Akola", "Latur", "Jalgaon", "Ahmednagar", "Sangli", "Kolhapur", "Chandrapur", "Parbhani", "Jalna", "Jalgaon", "Panvel", "Panvel", "Satara", "Beed", "Yavatmal", "Nagpur", "Gondia", "Solapur", "Amravati", "Osmanabad", "Nandurbar", "Wardha", "Latur", "Wardha", " " }));
        getContentPane().add(com_city);
        com_city.setBounds(510, 190, 126, 22);
        getContentPane().add(txt_pass);
        txt_pass.setBounds(510, 220, 130, 22);

        b_sub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b_sub.setText(" Submit");
        b_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_subActionPerformed(evt);
            }
        });
        getContentPane().add(b_sub);
        b_sub.setBounds(490, 260, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registration Form");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 10, 250, 40);

        jButton1.setText("welcome page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 390, 150, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\rvkul\\Documents\\NetBeansProjects\\myproj\\src\\myproj\\image\\man map.jpeg")); // NOI18N
        jLabel8.setText("welcome ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 10, 650, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_subActionPerformed
      
        
        
        String name=txt_name.getText();
        int contact=Integer.parseInt(txt_con.getText());
        String email=txt_email.getText();
        int adhar=Integer.parseInt(txt_adhar.getText());
        String city=com_city.getSelectedItem().toString();
        String pass=txt_pass.getText();
       
        //connection
        
        Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");  
             
                 
//    query for insert data into table 

                 
                 pst=con.prepareStatement("insert into reginfo values(?,?,?,?,?,?)");
            
            pst.setString(1,name);
            pst.setInt(2,contact);
            pst.setString(3,email);
            pst.setInt(4,adhar);
            pst.setString(5,city);
            pst.setString(6,pass);
            
              int i= pst.executeUpdate();
          if(i>0)
          {
              JOptionPane.showMessageDialog(null," save");
          }
          else{
              JOptionPane.showMessageDialog(null,"not save");
          }
            
            new Login().setVisible(true);
       this.setVisible(false);
            
}catch(Exception e){ System.out.println(e);} 
        

// TODO add your handling code here:
    }//GEN-LAST:event_b_subActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      new welcome().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reginfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reginfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reginfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reginfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reginfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_sub;
    private javax.swing.JComboBox com_city;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_adhar;
    private javax.swing.JTextField txt_con;
    public javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pass;
    // End of variables declaration//GEN-END:variables
}
