/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproj;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author rvkul
 */
public class upd_booking extends javax.swing.JFrame {

    /**
     * Creates new form upd_booking
     */
    public upd_booking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        B_city = new javax.swing.JButton();
        b_tocity = new javax.swing.JButton();
        b_date = new javax.swing.JButton();
        b_time = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        com_from = new javax.swing.JComboBox();
        com_to = new javax.swing.JComboBox();
        ch_date = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        com_time = new javax.swing.JComboBox();
        b_vehical = new javax.swing.JButton();
        com_car = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Change From city");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 122, 16);

        jLabel2.setText("Change To City");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 90, 100, 20);

        jLabel3.setText("Change Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 130, 90, 16);

        jLabel4.setText("Change Time");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 160, 105, 43);

        B_city.setText("Change ");
        B_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cityActionPerformed(evt);
            }
        });
        getContentPane().add(B_city);
        B_city.setBounds(250, 50, 80, 25);

        b_tocity.setText("change");
        b_tocity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tocityActionPerformed(evt);
            }
        });
        getContentPane().add(b_tocity);
        b_tocity.setBounds(250, 90, 73, 25);

        b_date.setText("change");
        b_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_dateActionPerformed(evt);
            }
        });
        getContentPane().add(b_date);
        b_date.setBounds(250, 130, 73, 25);

        b_time.setText("change");
        b_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_timeActionPerformed(evt);
            }
        });
        getContentPane().add(b_time);
        b_time.setBounds(250, 170, 73, 25);

        jButton5.setText(" Back To Booking Page");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(110, 250, 190, 25);

        com_from.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad", "Solapur", "Dhule", "Amaravati", "Nashik", "Kolhapur", "Nanded", "Sangli", "Thane", "Akola", "Latur", "Jalgaon", "Ahmednagar", "Sangli", "Kolhapur", "Chandrapur", "Parbhani", "Jalna", "Jalgaon", "Panvel", "Panvel", "Satara", "Beed", "Yavatmal", "Nagpur", "Gondia", "Solapur", "Amravati", "Osmanabad", "Nandurbar", "Wardha", "Latur", "Wardha", " " }));
        getContentPane().add(com_from);
        com_from.setBounds(144, 50, 80, 22);

        com_to.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad", "Solapur", "Dhule", "Amaravati", "Nashik", "Kolhapur", "Nanded", "Sangli", "Thane", "Akola", "Latur", "Jalgaon", "Ahmednagar", "Sangli", "Kolhapur", "Chandrapur", "Parbhani", "Jalna", "Jalgaon", "Panvel", "Panvel", "Satara", "Beed", "Yavatmal", "Nagpur", "Gondia", "Solapur", "Amravati", "Osmanabad", "Nandurbar", "Wardha", "Latur", "Wardha", " " }));
        getContentPane().add(com_to);
        com_to.setBounds(144, 90, 80, 20);

        ch_date.setDateFormatString("d-mmm-yyyy");
        getContentPane().add(ch_date);
        ch_date.setBounds(140, 130, 101, 22);

        jLabel5.setText("Change Vehical");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 210, 100, 30);

        com_time.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12  A.M", "1    A.M", "2    A.M", "3    A.M", "4    A.M", "5    A.M", "6    A.M", "7    A.M", "8    A.M", "9    A.M", "10  A.M", "11  A.M", "12  P.M", "1    P.M", "2    P.M", "3    P.M", "4    P.M", "5    P.M", "6    P.M", "7    P.M", "8    P.M", "9    P.M", "10  P.M", "11  P.M", "12  P.M" }));
        getContentPane().add(com_time);
        com_time.setBounds(140, 170, 100, 22);

        b_vehical.setText("change");
        b_vehical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_vehicalActionPerformed(evt);
            }
        });
        getContentPane().add(b_vehical);
        b_vehical.setBounds(250, 210, 73, 25);

        com_car.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Car", "Bus" }));
        getContentPane().add(com_car);
        com_car.setBounds(140, 210, 100, 22);

        jLabel6.setText("Email");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 10, 100, 20);
        getContentPane().add(txt_email);
        txt_email.setBounds(130, 10, 220, 22);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 320, 350, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\rvkul\\Documents\\NetBeansProjects\\myproj\\src\\myproj\\image\\map pin.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1, -4, 640, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cityActionPerformed
        //update from city  city
        
        
         String value=com_from.getSelectedItem().toString();
         String email=txt_email.getText();
        Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");
             //   pst=con.prepareStatement("insert into booking(email)select email from reginfo");
                    //UPDATE table_name SET field1 = new-value1, field2 = new-value2
                 
                 pst=con.prepareStatement("update booking set from_city=? where email=?");
                pst.setString(2,email);
                pst.setString(1, value);
                
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null,"booking update  successfully");
              
          }
          else{
              JOptionPane.showMessageDialog(null,"booking update not successfully");
          }
                 
                }
                
                catch(Exception e){ System.out.println(e);} 
             
    }//GEN-LAST:event_B_cityActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new home().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void b_tocityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tocityActionPerformed
       
        //to city
        
        String value1=com_to.getSelectedItem().toString();
        String email=txt_email.getText();
        Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");
             //   pst=con.prepareStatement("insert into booking(email)select email from reginfo");
                    //UPDATE table_name SET field1 = new-value1, field2 = new-value2
                 
                 pst=con.prepareStatement("update booking set to_city=? where email=?");
                
                pst.setString(1,value1);
                pst.setString(2,email);
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null,"booking  information update  successfully");
              
          }
          else{
             JOptionPane.showMessageDialog(null,"booking  information  not update  successfully");
          }
                
                }
                
                catch(Exception e){ System.out.println(e);} 
                
        
        
        
        
    }//GEN-LAST:event_b_tocityActionPerformed

    private void b_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_dateActionPerformed
Date date= new Date(ch_date.getDate().getTime());
      DateFormat dateFormat=new SimpleDateFormat("d-mmm-yyyy");
      String strDate=dateFormat.format(date);
         String email=txt_email.getText();
        
        Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");
             //   pst=con.prepareStatement("insert into booking(email)select email from reginfo");
                    //UPDATE table_name SET field1 = new-value1, field2 = new-value2
                 
                 pst=con.prepareStatement("update booking set date=? where email=?");
                
                pst.setDate(1,date);
                pst.setString(2,email);
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null,"booking  information update  successfully");
              
          }
          else{
              JOptionPane.showMessageDialog(null,"booking  information  not update  successfully");
          }
                  
                }
                
                catch(Exception e){ System.out.println(e);} 
                
         
    }//GEN-LAST:event_b_dateActionPerformed

    private void b_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_timeActionPerformed
        // TODO add your handling code here:
        String time=com_time.getSelectedItem().toString();
        String email=txt_email.getText();
        
         Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");
             //   pst=con.prepareStatement("insert into booking(email)select email from reginfo");
                    //UPDATE table_name SET field1 = new-value1, field2 = new-value2
                 
                 pst=con.prepareStatement("update booking set time=? where email=?");
                
                pst.setString(1,time);
                pst.setString(2,email);
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null,"booking  information update  successfully");
              
          }
          else{
              JOptionPane.showMessageDialog(null,"booking  information  not update  successfully");
          }
                
                }
                
                catch(Exception e){ System.out.println(e);} 
                
        
        
    }//GEN-LAST:event_b_timeActionPerformed

    private void b_vehicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_vehicalActionPerformed
      
      String email=txt_email.getText();  
        String value3=com_car.getSelectedItem().toString();
        Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","dbms1414");
             //   pst=con.prepareStatement("insert into booking(email)select email from reginfo");
                    //UPDATE table_name SET field1 = new-value1, field2 = new-value2
                 
                 pst=con.prepareStatement("update booking set vehicle=? where email=?");
                
                pst.setString(1,value3);
                pst.setString(2,email);
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null,"booking  information update  successfully");
              
          }
          else{
            JOptionPane.showMessageDialog(null,"booking  information  not update  successfully");
          }
                
                }
                
                catch(Exception e){ System.out.println(e);} 
                
        
        
        
        
      
    }//GEN-LAST:event_b_vehicalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(upd_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(upd_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(upd_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(upd_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new upd_booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_city;
    private javax.swing.JButton b_date;
    private javax.swing.JButton b_time;
    private javax.swing.JButton b_tocity;
    private javax.swing.JButton b_vehical;
    private com.toedter.calendar.JDateChooser ch_date;
    private javax.swing.JComboBox com_car;
    private javax.swing.JComboBox com_from;
    private javax.swing.JComboBox com_time;
    private javax.swing.JComboBox com_to;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_email;
    // End of variables declaration//GEN-END:variables
}
